name: PHPUnit Tests

on: [ push, pull_request, workflow_dispatch ]

concurrency:
  group: main
  cancel-in-progress: true

permissions: {}

jobs:
  phpunit:
    name: ${{ matrix.php-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [ 7.4, 8.3 ]

    services:
      mysql:
        image: mariadb:latest
        ports:
          - '3306:3306'
        env:
          MYSQL_ROOT_PASSWORD: wordpress
          MARIADB_INITDB_SKIP_TZINFO: 1
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: wordpress
          MYSQL_DATABASE: wordpress_test

    steps:
      - name: Check out the source code
        uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        name: Set up PHP
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none

      - name: Install PHP Dependencies
        uses: ramsey/composer-install@v2

      - name: Set up WordPress and WordPress Test Library
        uses: sjinks/setup-wordpress-test-library@master
        with:
          version: latest

      - name: Verify MariaDB connection
        run: |
          while ! mysqladmin ping -h 127.0.0.1 -P ${{ job.services.mysql.ports[3306] }} --silent; do
            sleep 1
          done
        timeout-minutes: 1

      - name: Run
        run: vendor/bin/phpunit
